name: flutter_clima
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gradients: ^1.0.0+3
  font_awesome: ^5.10.1
  geolocator: ^7.0.1
  google_fonts: ^2.0.0
  lottie: ^1.0.1
  sizer: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
