import 'package:flutter/material.dart';
import 'package:flutter_clima/data/controllers/weather_controller.dart';
import 'package:flutter_clima/data/models/weather.dart';
import 'package:flutter_clima/widgets/weather_content.dart';
import 'package:flutter_clima/utilities/constants.dart';
import 'package:lottie/lottie.dart';
part 'location_screen.dart';
part 'loading_screen.dart';
part 'city_screen.dart';
